"""add_seller_profiles_and_documents

Revision ID: 2ae521447228
Revises:
Create Date: 2026-08-11 17:20:29.579107

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ae521447228"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    document_type = postgresql.ENUM(
        "pan_card",
        "bank_statement",
        "iec_certificate",
        "gst_certificate",
        "other",
        name="document_type",
        create_type=False,
    )
    document_type.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "seller_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("firm_name", sa.String(length=255), nullable=False),
        sa.Column("owner_name", sa.String(length=255), nullable=True),
        sa.Column("pan_encrypted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("bank_name", sa.String(length=255), nullable=True),
        sa.Column("bank_account_encrypted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ifsc", sa.String(length=11), nullable=True),
        sa.Column("bank_branch", sa.String(length=255), nullable=True),
        sa.Column("iec", sa.String(length=10), nullable=True),
        sa.Column("ad_code_encrypted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("gstin_encrypted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("pincode", sa.String(length=10), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iec"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "profile_documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", document_type, nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("encrypted_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["seller_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_documents")
    op.drop_table("seller_profiles")
    sa.Enum(name="document_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
