"""add orders

Revision ID: 4798bbcd2ff3
Revises: a1f4c9e2b7d6
Create Date: 2026-08-11 11:28:22.700491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4798bbcd2ff3"
down_revision: Union[str, Sequence[str], None] = "a1f4c9e2b7d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "quote_accepted",
                "confirmed",
                "paid_held",
                "in_transit",
                "delivered",
                "disputed",
                "settled",
                "refunded",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "validation_state",
            sa.Enum("incomplete", "invalid", "ready", name="validation_state"),
            nullable=True,
        ),
        sa.Column("destination_country", sa.String(length=64), nullable=True),
        sa.Column("value_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("consignee", sa.String(length=256), nullable=True),
        sa.Column("net_weight_g", sa.Integer(), nullable=True),
        sa.Column("gross_weight_g", sa.Integer(), nullable=True),
        sa.Column("article_id", sa.String(length=128), nullable=True),
        sa.Column("iec", sa.String(length=16), nullable=True),
        sa.Column("gstin", sa.String(length=16), nullable=True),
        sa.Column("ad_code", sa.String(length=16), nullable=True),
        sa.Column("bank_account", sa.String(length=32), nullable=True),
        sa.Column("bank_name", sa.String(length=128), nullable=True),
        sa.Column("ifsc", sa.String(length=16), nullable=True),
        sa.Column("quote_id", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
