"""initial schema

Revision ID: 8d3617703da2
Revises:
Create Date: 2026-08-09 11:00:17.744305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d3617703da2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_flags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flag_key", sa.String(length=128), nullable=False),
        sa.Column("flag_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flag_key"),
    )
    op.create_table(
        "country_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_iso2", sa.String(length=2), nullable=False),
        sa.Column("hs6", sa.String(length=6), nullable=True),
        sa.Column("rate_type", sa.String(length=32), nullable=False),
        sa.Column("rate_pct", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=True),
        sa.Column("threshold_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("basis", sa.String(length=64), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("structured_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("supersedes_doc_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_doc_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lanes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lane", sa.String(length=4), nullable=False),
        sa.Column("country_iso2", sa.String(length=2), nullable=False),
        sa.Column("first_slab_g", sa.Integer(), nullable=False),
        sa.Column("first_slab_rate_minor", sa.Integer(), nullable=False),
        sa.Column("addl_slab_g", sa.Integer(), nullable=False),
        sa.Column("addl_slab_rate_minor", sa.Integer(), nullable=False),
        sa.Column("weight_cap_g", sa.Integer(), nullable=True),
        sa.Column("volume_free", sa.Boolean(), nullable=False),
        sa.Column("divisor", sa.Integer(), nullable=True),
        sa.Column("transit_min_days", sa.Integer(), nullable=True),
        sa.Column("transit_max_days", sa.Integer(), nullable=True),
        sa.Column("conflicts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("lane IN ('ITPS', 'EMS')", name="ck_lanes_lane"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pbe_field_schemas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_type", sa.String(length=16), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=True),
        sa.Column("field_key", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("validation", sa.String(), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("hs6_default", sa.String(length=10), nullable=True),
        sa.Column("pbe_desc_template", sa.String(), nullable=True),
        sa.Column("certifications", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("lane_fit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "state_sales_tax",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state_iso2", sa.String(length=2), nullable=False),
        sa.Column("state_name", sa.String(length=64), nullable=False),
        sa.Column("state_rate_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("combined_min_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("combined_max_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("nexus_threshold_usd", sa.Integer(), nullable=True),
        sa.Column("nexus_tx_test", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_iso2"),
    )
    op.create_table(
        "transcripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hs_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hs6", sa.String(length=6), nullable=False),
        sa.Column("itc_hs_8", sa.String(length=8), nullable=True),
        sa.Column("hts_10", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("product_cat", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_level", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_cat"],
            ["product_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lookups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("category_key", sa.String(length=100), nullable=False),
        sa.Column("hs_code", sa.String(length=10), nullable=True),
        sa.Column("duty", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("lane", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lookups")
    op.drop_table("hs_codes")
    op.drop_table("transcripts")
    op.drop_table("state_sales_tax")
    op.drop_table("product_categories")
    op.drop_table("pbe_field_schemas")
    op.drop_table("lanes")
    op.drop_table("documents")
    op.drop_table("country_rates")
    op.drop_table("config_flags")
    # ### end Alembic commands ###
