"""add exporter fields to orders

Revision ID: b02939665e2f
Revises: 0bcc473d5046
Create Date: 2026-08-11 13:19:40.399690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b02939665e2f"
down_revision: Union[str, Sequence[str], None] = "0bcc473d5046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("exporter_name", sa.String(length=256), nullable=True))
    op.add_column("orders", sa.Column("exporter_address", sa.String(length=512), nullable=True))
    op.add_column("orders", sa.Column("state_code", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "state_code")
    op.drop_column("orders", "exporter_address")
    op.drop_column("orders", "exporter_name")
    # ### end Alembic commands ###
